CONFIG_SUPPORT_ATCMD=y
CONFIG_ATCMD_NETWORK=y
CONFIG_VFS_LITTLEFS_INCLUDED=y
CONFIG_KERNEL=y
CONFIG_MBEDTLS_ENABLED_MENU=y
CONFIG_LVGL=y
CONFIG_LVGL_V9_5=y
CONFIG_LVGL_COLOR_DEPTH=16
CONFIG_LVGL_MEMORY_SIZE=131072
CONFIG_LVGL_USE_OS=2
CONFIG_LVGL_DISPLAY_DRIVER="ST7701S"
CONFIG_LVGL_DISPLAY_WIDTH=480
CONFIG_LVGL_DISPLAY_HEIGHT=800
CONFIG_LVGL_DOUBLE_BUFFER=y
CONFIG_LVGL_DEMO_MUSIC=y
CONFIG_LVGL_DEMO_MUSIC_AUTO_PLAY=y
CONFIG_LVGL_USE_LOG=y
CONFIG_LVGL_USE_ASSERT=n