SUPPORT_ATCMD=y
ATCMD_NETWORK=y
VFS_LITTLEFS_INCLUDED=y
KERNEL=y
MBEDTLS_ENABLED_MENU=y
LVGL=y
LVGL_V9_5=y
LVGL_DISPLAY_DRIVER=ST7701S
LVGL_DISPLAY_WIDTH=480
LVGL_DISPLAY_HEIGHT=800
LVGL_COLOR_DEPTH=16
LVGL_DOUBLE_BUFFER=y
LVGL_MEMORY_SIZE=131072
LVGL_USE_OS=2
LVGL_DEMO_MUSIC=y
LVGL_DEMO_MUSIC_AUTO_PLAY=y
LVGL_USE_LOG=y
LVGL_USE_ASSERT=n